package com.example.roommvvm;


import android.arch.persistence.room.Entity;
import android.arch.persistence.room.PrimaryKey;

@Entity(tableName = "note_table")
public class Note {


    @PrimaryKey (autoGenerate = true)   //So the Id will be automatically generated
    private int Id;

    private String Title;

    private String Description;

    private String priority;


    public Note(String title, String description, String priority) {
        this.Title = title;
        this.Description = description;
        this.priority = priority;
    }

    //And the setter here because it is autogenerated and not present in the constructor
    public void setId(int id) {
        this.Id = id;
    }


    //We make the getter in order to get sources from the database
    public int getId() {
        return Id;
    }

    public String getTitle() {
        return Title;
    }

    public String getDescription() {
        return Description;
    }

    public String getPriority() {
        return priority;
    }
}
